//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_login_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_commande_achat
    {
        public short Commande_A { get; set; }
        public short Produit { get; set; }
        public Nullable<int> Quantite { get; set; }
    
        public virtual commande_achat commande_achat { get; set; }
        public virtual produit produit1 { get; set; }
    }
}
