//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_login_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class commerciaEntities : DbContext
    {
        public commerciaEntities()
            : base("name=commerciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande_achat> commande_achat { get; set; }
        public virtual DbSet<commande_vente> commande_vente { get; set; }
        public virtual DbSet<fournisseur> fournisseur { get; set; }
        public virtual DbSet<ligne_commande_achat> ligne_commande_achat { get; set; }
        public virtual DbSet<ligne_commande_vente> ligne_commande_vente { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<type_produit> type_produit { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
