//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_login_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.ligne_commande_achat = new HashSet<ligne_commande_achat>();
            this.ligne_commande_vente = new HashSet<ligne_commande_vente>();
        }
    
        public short Num_P { get; set; }
        public string Libelle { get; set; }
        public string Type_P { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Image_Nom { get; set; }
        public string Description_P { get; set; }
        public Nullable<int> Quantite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_commande_achat> ligne_commande_achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_commande_vente> ligne_commande_vente { get; set; }
        public virtual type_produit type_produit { get; set; }
    }
}
